### ISSUE TITLE
Terminated scalable run got stuck in Finilazing

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#208]
The run was terminated from UI and all VMs were properly killed, however the run is in Finilazing
https://bb1.hnx.helix-nebula.eu/run/57537e45-f34c-4915-886e-9ce889134761
I haven't tried to reproduce it yet.

This might be related to the completion of the states by the node instances.

**Comment by konstan** [comment]
Just an update.  I still rather frequently see this on nuv.la.

**Comment by loomis** [comment]
0.5 day time-boxed investigation

**Comment by konstan** [comment]
Just noticed.  Failure terminating VM on cloud layer (Exoscale) lead to `500` and the scalable run stayed in Finalizing.  Still need to verify if the issues are related.

https://nuv.la/run/bfd39ce0-a36e-4373-9729-8f740b74d2fd

```
 2016-02-09T15:13:38.926+0000 SEVERE com.sixsq.slipstream.util.ProcessUtils execGetOutputAsArray Error executing: sh -c /usr/bin/cloudstack-terminate-instances --password 'xxx' --endpoint '
https://api.exoscale.ch/compute' --zone 'CH-GV2' --username 'MEKtgh8swrU1wVU4Qf7aYKFVVxUOB_cLvsoW25pQMsJxYI6J6Y4UuK-SfeFdaZs-l8YEnblF3WXd0_4t9igmsA'  --instance-ids-file /opt/slipstream/server/tmp/instance-ids373489133579728483.tmp . With exit code = 2 and stdout:
: 2016-02-09T15:13:29Z :
==== Initialize the CloudStack connector.
/usr/lib/python2.6/site-packages/libcloud/httplib_ssl.py:229: UserWarning: SSL certificate verification is disabled, this can pose a security risk. For more information how to enable the SSL certificate verification, please visit the libcloud documentation.
  warnings.warn(libcloud.security.VERIFY_SSL_DISABLED_MSG)

: 2016-02-09T15:13:32Z :
    Failed to get max.iaas.workers: <type 'exceptions.KeyError'> 'node_instance_name'
Unable to destroy VM[User|i-519-62705-VM]
 and stderr:
 2016-02-09T15:13:38.926+0000 WARNING org.restlet.resource.ServerResource doCatch Exception or error caught in server resource

Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
        at org.restlet.resource.ServerResource.delete(ServerResource.java:181)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:456)
        at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:683)
        at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
        at org.restlet.resource.ServerResource.handle(ServerResource.java:1014)
        at org.restlet.resource.Finder.handle(Finder.java:246)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at com.sixsq.slipstream.application.RootApplication$RootRouter.doHandle(RootApplication.java:484)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
        at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
        at org.restlet.Application.handle(Application.java:384)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.routing.Router.doHandle(Router.java:431)
        at org.restlet.routing.Router.handle(Router.java:648)
        at org.restlet.routing.Filter.doHandle(Filter.java:159)
        at org.restlet.routing.Filter.handle(Filter.java:206)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
        at org.restlet.Component.handle(Component.java:406)
        at org.restlet.Server.handle(Server.java:516)
        at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:72)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:152)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1118)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.sixsq.slipstream.exceptions.ProcessException:
: 2016-02-09T15:13:29Z :
==== Initialize the CloudStack connector.
/usr/lib/python2.6/site-packages/libcloud/httplib_ssl.py:229: UserWarning: SSL certificate verification is disabled, this can pose a security risk. For more information how to enable the SSL certificate verification, please visit the libcloud documentation.
  warnings.warn(libcloud.security.VERIFY_SSL_DISABLED_MSG)

: 2016-02-09T15:13:32Z :
    Failed to get max.iaas.workers: <type 'exceptions.KeyError'> 'node_instance_name'
Unable to destroy VM[User|i-519-62705-VM]

        at com.sixsq.slipstream.util.ProcessUtils.execGetOutputAsArray(ProcessUtils.java:123)
        at com.sixsq.slipstream.util.ProcessUtils.execGetOutputAsArray(ProcessUtils.java:69)
        at com.sixsq.slipstream.util.ProcessUtils.execGetOutput(ProcessUtils.java:44)
        at com.sixsq.slipstream.connector.CliConnectorBase.terminate(CliConnectorBase.java:195)
        at com.sixsq.slipstream.util.Terminator.terminateInstances(Terminator.java:111)
        at com.sixsq.slipstream.util.Terminator.terminate(Terminator.java:98)
        at com.sixsq.slipstream.run.RunResource.terminate(RunResource.java:159)
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:524)
        ... 74 more
2016-02-09T15:13:39.028+0000 INFO org.restlet.engine.log.LogFilter afterHandle 2016-02-09       15:13:39        127.0.0.1       -       127.0.0.1       80      DELETE  /run/bfd39ce0-a36e-4373-9729-8f740b74d2fd       -       500     19875   0       10278   https://nuv.la  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36       https://nuv.la/run/bfd39ce0-a36e-4373-9729-8f740b74d2fd
```

**Comment by konstan** [comment]
After upgrade of `nuv.la

**Comment by konstan** [comment]
According to Exoscale they've acknowledged and fixed the issue on their side https://portal.exoscale.ch/tickets/1009038
