### ISSUE TITLE
ss bootstrap fails on CentOS 7 "cannot import name _compare_digest"

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#253]
Noticed this on `Linux CentOS 7.1 64-bit` image on Exoscale.

```
[root@orchestrator-exoscalefb5d468e-1051-4907-989b-ea45ee990511 ~]# cat /var/log/slipstream/client/orchestrator-exoscale.slipstream.log
/var/lib/cloud/instance/scripts/part-001: line 14: wget: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23034  100 23034    0     0  70431      0 --:--:-- --:--:-- --:--:-- 70440
warning: /var/cache/yum/x86_64/7/base/packages/python-setuptools-0.9.8-4.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-1.1503.el7.centos.2.7.x86_64 (installed)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
==============================
=== orchestrator bootstrap ===
==============================
Retrieving the latest version of the SlipStream from: http://83.157.98.20:50001/downloads/slipstreamclient.tgz
Expanding tarball: /opt/slipstream/client/slipstreamclient.tgz
Creating local environment variable script for manual troubleshooting
Published abort message to http://83.157.98.20:50000/run/fb5d468e-1051-4907-989b-ea45ee990511/ss:abort
Traceback (most recent call last):
  File "/opt/slipstream/slipstream.bootstrap", line 695, in <module>
    main()
  File "/opt/slipstream/slipstream.bootstrap", line 629, in main
    setup_ss_and_cloud_connector(is_orchestration)
  File "/opt/slipstream/slipstream.bootstrap", line 599, in setup_ss_and_cloud_connector
    get_and_setup_ss(cloud, is_orchestration)
  File "/opt/slipstream/slipstream.bootstrap", line 583, in get_and_setup_ss
    _paramikoSetup()
  File "/opt/slipstream/slipstream.bootstrap", line 329, in _paramikoSetup
    import paramiko  # noqa
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 55, in <module>
    from paramiko.packet import Packetizer, NeedRekeyException
  File "/usr/lib/python2.7/site-packages/paramiko/packet.py", line 29, in <module>
    from hmac import HMAC
  File "/usr/lib64/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
[root@orchestrator-exoscalefb5d468e-1051-4907-989b-ea45ee990511 ~]#

[root@orchestrator-exoscalefb5d468e-1051-4907-989b-ea45ee990511 ~]# pip freeze
backports.ssl-match-hostname==3.4.0.2
boto==2.25.0
chardet==2.0.1
Cheetah==2.4.4
cloud-init==0.7.5
configobj==4.7.2
decorator==3.4.0
ecdsa==0.13
iniparse==0.4
IPy==0.75
jsonpatch==1.2
jsonpointer==1.0
kitchen==1.1.1
Markdown==2.4.1
paramiko==1.15.3
Pillow==2.0.0
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pycrypto==2.6.1
pycurl==7.19.0
Pygments==1.4
pygobject==3.8.2
pygpgme==0.3
pyliblzma==0.5.3
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.10
requests==1.1.0
scpclient==0.4
seobject==0.1
sepolicy==1.1
six==1.3.0
urlgrabber==3.10
urllib3==1.5
yum-metadata-parser==1.1.4
[root@orchestrator-exoscalefb5d468e-1051-4907-989b-ea45ee990511 ~]#

[root@orchestrator-exoscalefb5d468e-1051-4907-989b-ea45ee990511 ~]# rpm -qa | grep python
python-pillow-2.0.0-17.gitd1c6db8.el7.x86_64
python-cheetah-2.4.4-5.el7.centos.x86_64
python-libs-2.7.5-34.el7.x86_64
python-devel-2.7.5-34.el7.x86_64
libselinux-python-2.2.2-6.el7.x86_64
python-kitchen-1.1.1-5.el7.noarch
python-jsonpointer-1.0-2.el7.centos.noarch
python-prettytable-0.7.2-2.el7.centos.noarch
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
python-pyudev-0.15-6.el7.noarch
python-IPy-0.75-6.el7.noarch
libsemanage-python-2.1.10-16.el7.x86_64
python-pycurl-7.19.0-17.el7.x86_64
newt-python-0.52.15-4.el7.x86_64
audit-libs-python-2.4.1-5.el7.x86_64
python-urllib3-1.5-8.el7.noarch
python-markdown-2.4.1-1.el7.centos.noarch
policycoreutils-python-2.2.5-15.el7.x86_64
python-pygments-1.4-9.el7.noarch
python-setuptools-0.9.8-4.el7.noarch
python-2.7.5-34.el7.x86_64
python-decorator-3.4.0-3.el7.noarch
dbus-python-1.1.1-9.el7.x86_64
python-chardet-2.0.1-7.el7.noarch
python-configobj-4.7.2-7.el7.noarch
python-jsonpatch-1.2-3.el7.centos.noarch
python-backports-1.0-8.el7.x86_64
python-iniparse-0.4-9.el7.noarch
python-boto-2.25.0-2.el7.centos.noarch
python-urlgrabber-3.10-6.el7.noarch
python-six-1.3.0-4.el7.noarch
python-requests-1.1.0-8.el7.noarch
rpm-python-4.11.1-25.el7.x86_64
[root@orchestrator-exoscalefb5d468e-1051-4907-989b-ea45ee990511 ~]#
```

**Comment by schaubl** [comment]
@konstan: I think this has been fixed. Am I right ?
