### ISSUE TITLE
on a clean machine an number of tests fail to find slipstream.context

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#254]
Examples
```
======================================================================
ERROR: Failure: ConfigurationError (Failed to find local configuration file.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/test/python/TestBaseCloudConnector.py", line 28, in <module>
    from slipstream.cloudconnectors.BaseCloudConnector import BaseCloudConnector
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/cloudconnectors/BaseCloudConnector.py", line 42, in <module>
    from slipstream.executors.MachineExecutor import MachineExecutor
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/executors/MachineExecutor.py", line 38, in <module>
    class MachineExecutor(object):
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/executors/MachineExecutor.py", line 48, in MachineExecutor
    def __init__(self, wrapper, config_holder=ConfigHolder()):
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/ConfigHolder.py", line 54, in __init__
    self.context = context or ContextualizerFactory.getContextAsDict()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/ContextualizerFactory.py", line 29, in getContextAsDict
    contextualizer = ContextualizerFactory.createContextualizer()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/ContextualizerFactory.py", line 25, in createContextualizer
    return LocalContextualizer()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 51, in __init__
    self._load()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 57, in _load
    self.parser = self._getParser()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 61, in _getParser
    self.configFile = self._getConfigFile()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 71, in _getConfigFile
    raise Exceptions.ConfigurationError('Failed to find local configuration file.')
ConfigurationError: Failed to find local configuration file.

======================================================================
ERROR: test_getAvailableCloudConnectorsModuleNames (TestCloudConnectorFactory.TestCloudConnectorFactory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/test/python/TestCloudConnectorFactory.py", line 32, in test_getAvailableCloudConnectorsModuleNames
    for module_name in self.get_cloudconnector_modulenames():
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/test/python/TestCloudConnectorsBase.py", line 38, in get_cloudconnector_modulenames
    return get_cloudconnector_modulenames(base_package=base_package)
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/util.py", line 129, in get_cloudconnector_modulenames
    if hasattr(loadModule(name), 'getConnector'):
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/util.py", line 483, in loadModule
    return __import__(name, fromlist=namespace)
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/cloudconnectors/dummy/DummyClientCloud.py", line 20, in <module>
    from slipstream.cloudconnectors.BaseCloudConnector import BaseCloudConnector
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/cloudconnectors/BaseCloudConnector.py", line 42, in <module>
    from slipstream.executors.MachineExecutor import MachineExecutor
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/executors/MachineExecutor.py", line 38, in <module>
    class MachineExecutor(object):
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/executors/MachineExecutor.py", line 48, in MachineExecutor
    def __init__(self, wrapper, config_holder=ConfigHolder()):
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/ConfigHolder.py", line 54, in __init__
    self.context = context or ContextualizerFactory.getContextAsDict()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/ContextualizerFactory.py", line 29, in getContextAsDict
    contextualizer = ContextualizerFactory.createContextualizer()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/ContextualizerFactory.py", line 25, in createContextualizer
    return LocalContextualizer()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 51, in __init__
    self._load()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 57, in _load
    self.parser = self._getParser()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 61, in _getParser
    self.configFile = self._getConfigFile()
  File "/root/SlipStreamBootstrap/SlipStreamClient/client/target/main/python/slipstream/contextualizers/dummy/LocalContextualizer.py", line 71, in _getConfigFile
    raise Exceptions.ConfigurationError('Failed to find local configuration file.')
ConfigurationError: Failed to find local configuration file.
```

**Comment by schaubl** [comment]
@konstan: Is it fixed ?

**Comment by loomis** [comment]
This was fixed a couple of releases ago.  Closing...
