### ISSUE TITLE
dependency issue at runtime on v3.37-snapshot  "No module named Crypto.PublicKey"

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#349]
```
 2017-09-29T12:48:01.271+0000 SEVERE com.sixsq.slipstream.util.ProcessUtils execGetOutputAsArray Error executing: sh -c /usr/bin/exoscale-run-instances --native-contextualization 'linux-only' --zone 'CH-GVA-2' --disk-size '10G' --instance-type 'Micro' --security-groups 'slipstream_managed' --login-username '' --username 'xxx' --image-id 'Linux Ubuntu 14.04 LTS 64-bit' --network-type 'Public'  . With exit code = 1 and stdout:  and stderr: Traceback (most recent call last):
  File "/usr/bin/exoscale-run-instances", line 7, in <module>
    from slipstream_exoscale.ExoscaleCommand import ExoscaleCommand
  File "/usr/lib/python2.7/site-packages/slipstream_exoscale/ExoscaleCommand.py", line 19, in <module>
    from slipstream_cloudstack.CloudStackCommand import CloudStackCommand
  File "/usr/lib/python2.7/site-packages/slipstream_cloudstack/CloudStackCommand.py", line 20, in <module>
    from slipstream_cloudstack.CloudStackClientCloud import CloudStackClientCloud
  File "/usr/lib/python2.7/site-packages/slipstream_cloudstack/CloudStackClientCloud.py", line 27, in <module>
    from slipstream.cloudconnectors.BaseCloudConnector import BaseCloudConnector
  File "/usr/lib/python2.7/site-packages/slipstream/cloudconnectors/BaseCloudConnector.py", line 33, in <module>
    from slipstream.utils.ssh import remoteRunScriptNohup, waitUntilSshCanConnectOrTimeout, remoteRunScript, \
  File "/usr/lib/python2.7/site-packages/slipstream/utils/ssh.py", line 32, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey

```

```
[root@machineed37240f-5bdb-4549-80b7-2e054a6c3b75 ~]# rpm -qa --last | grep slipstream
slipstream-connector-stratuslab-python-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:52 AM UTC
slipstream-connector-stratuslab-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:52 AM UTC
slipstream-connector-otc-python-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:48 AM UTC
slipstream-connector-otc-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:48 AM UTC
slipstream-connector-openstack-python-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:46 AM UTC
slipstream-connector-openstack-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:46 AM UTC
slipstream-connector-opennebula-python-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:43 AM UTC
slipstream-connector-opennebula-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:43 AM UTC
slipstream-connector-nuvlabox-python-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:43 AM UTC
slipstream-connector-nuvlabox-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:43 AM UTC
slipstream-connector-nativesoftlayer-python-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:41 AM UTC
slipstream-connector-nativesoftlayer-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:41 AM UTC
slipstream-connector-exoscale-python-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:34 AM UTC
slipstream-connector-exoscale-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:34 AM UTC
slipstream-connector-cloudstack-python-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:34 AM UTC
slipstream-connector-cloudstack-3.37-1211.el7.noarch Fri 29 Sep 2017 11:53:34 AM UTC
slipstream-connector-ec2-python-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:31 AM UTC
slipstream-connector-ec2-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:31 AM UTC
slipstream-connector-azure-python-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:27 AM UTC
slipstream-connector-azure-3.37-1232.el7.noarch Fri 29 Sep 2017 11:53:27 AM UTC
slipstream-riemann-3.37-939.el7.noarch        Fri 29 Sep 2017 11:51:29 AM UTC
slipstream-pricing-server-3.37-1489.el7.noarch Fri 29 Sep 2017 11:50:55 AM UTC
slipstream-ring-container-3.37-1489.el7.noarch Fri 29 Sep 2017 11:50:51 AM UTC
slipstream-server-nginx-conf-3.37-939.el7.noarch Fri 29 Sep 2017 11:50:45 AM UTC
slipstream-server-3.37-1489.el7.noarch        Fri 29 Sep 2017 11:50:08 AM UTC
slipstream-client-clojure-3.37-1138.el7.noarch Fri 29 Sep 2017 11:49:52 AM UTC
libcloud-slipstream-downloads-3.37-939.el7.noarch Fri 29 Sep 2017 11:49:52 AM UTC
slipstream-ssclj-3.37-1489.el7.noarch         Fri 29 Sep 2017 11:49:50 AM UTC
slipstream-client-3.37-1078.el7.noarch        Fri 29 Sep 2017 11:49:31 AM UTC
slipstream-graphite-3.37-939.el7.noarch       Fri 29 Sep 2017 11:48:42 AM UTC
slipstream-useradd-3.37-939.el7.noarch        Fri 29 Sep 2017 11:48:18 AM UTC
slipstream-hsqldb-3.37-939.el7.noarch         Fri 29 Sep 2017 11:48:18 AM UTC
slipstream-es-repo-3.37-939.el7.noarch        Fri 29 Sep 2017 11:47:45 AM UTC
slipstream-repos-2.3-1.noarch                 Fri 29 Sep 2017 11:47:39 AM UTC
[root@machineed37240f-5bdb-4549-80b7-2e054a6c3b75 ~]#
```

**Comment by konstan** [comment]
```
[root@machineed37240f-5bdb-4549-80b7-2e054a6c3b75 ~]# pip freeze
apache-libcloud==0.18.0
Babel==0.9.6
backports.ssl-match-hostname==3.4.0.2
boto==2.45.0
carbon==0.9.16
certifi==2017.7.27.1
cffi==1.6.0
chardet==3.0.4
Cheetah==2.4.4
click==6.7
cloud-init==0.7.9
configobj==4.7.2
configparser==3.5.0
cryptography==1.7.2
decorator==3.4.0
defusedxml==0.5.0
enum34==1.0.4
et-xmlfile==1.0.1
httplib2==0.9.2
idna==2.6
importlib==1.0.4
iniparse==0.4
ipaddress==1.0.16
IPy==0.75
isodate==0.5.4
javapackages==1.0.0
jdcal==1.3
Jinja2==2.7.2
jsonpatch==1.2
jsonpointer==1.9
kitchen==1.1.1
lxml==3.2.1
Markdown==2.4.1
MarkupSafe==0.11
openpyxl==2.4.8
paramiko==2.1.1
perf==0.1
Pillow==2.0.0
ply==3.4
policycoreutils-default-encoding==0.1
prettytable==0.7.2
prompt-toolkit==1.0.15
pyasn1==0.1.9
pycparser==2.14
pycurl==7.19.0
Pygments==2.2.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyOpenSSL==0.13.1
pyserial==2.6
python-ldap==2.4.15
python-linux-procfs==0.4.9
pyudev==0.15
pywinrm==0.0.1
pyxattr==0.5.1
PyYAML==3.10
requests==2.18.4
rsa==3.4.1
schedutils==0.4
scpclient==0.4
seobject==0.1
sepolicy==1.1
six==1.11.0
slipstream-api==0.8.3
SoftLayer==5.2.14
Twisted-Core==12.2.0
urlgrabber==3.10
urllib3==1.22
virtualenv==1.10.1
wcwidth==0.1.7
whisper==0.9.16
xmlwitch==0.3
yum-metadata-parser==1.1.4
zope.interface==4.0.5
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@machineed37240f-5bdb-4549-80b7-2e054a6c3b75 ~]#
```

**Comment by konstan** [comment]
`yum install -y python-crypto` solves the issue.  We need to add this dependency on `slipstream-client`.  
`python-paramiko` requires 
```
# rpm -qR python-paramiko | grep crypto
python-cryptography
#
```
which neither provides nor brings the required dependency library.

**Comment by konstan** [comment]
Done in https://github.com/slipstream/SlipStreamClient/commit/0edfb2d25d4f4f73cac6c68509022bb5f729cd6b
