### ISSUE TITLE
when retrieving User use CIMI resources

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#385]
This requires changes in ACLs of connector configurations (https://github.com/slipstream/SlipStreamServer/issues/1401).

**Comment by 0xbase12** [comment]
I have this issue with the current implementation:

```
com.sixsq.slipstream.exceptions.ProcessException: Usage: exoscale-run-instances [options]

exoscale-run-instances: error: no such option: --username

	at com.sixsq.slipstream.util.ProcessUtils.execGetOutputAsArray(ProcessUtils.java:123)
	at com.sixsq.slipstream.util.ProcessUtils.execGetOutputAsArray(ProcessUtils.java:69)
	at com.sixsq.slipstream.util.ProcessUtils.execGetOutput(ProcessUtils.java:59)
	at com.sixsq.slipstream.connector.CliConnectorBase.launch(CliConnectorBase.java:125)
	at com.sixsq.slipstream.connector.Launcher$SyncLauncher.launchRun(Launcher.java:106)
	at com.sixsq.slipstream.connector.Launcher$SyncLauncher.launch(Launcher.java:90)
	at com.sixsq.slipstream.connector.Launcher$SyncLauncher.run(Launcher.java:82)
	at com.sixsq.slipstream.connector.Launcher.launch(Launcher.java:48)
	at slipstream.async.launcher$launch_BANG_$fn__585$state_machine__7331__auto____592$fn__594.invoke(launcher.clj:51)
	at slipstream.async.launcher$launch_BANG_$fn__585$state_machine__7331__auto____592.invoke(launcher.clj:51)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at slipstream.async.launcher$launch_BANG_$fn__585.invoke(launcher.clj:51)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by konstan** [comment]
@0xbase12 Looking into this now.  Though, not yet sure it's related to this ticket.

**Comment by konstan** [comment]
@0xbase12 I was wrong.  It's related.  Will be fixing now.

**Comment by konstan** [comment]
@0xbase12 1ad7dc9 fixes the issue as part of the PR https://github.com/slipstream/SlipStreamClient/pull/387
