### ISSUE TITLE
'maximum recursion depth exceeded' on mutable run in MachineExecutor._execute()

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#77]
After running for a week in the mutual deployment NodeExecutors failed with `Error executing node, with detail: maximum recursion depth exceeded`.

Here is the number of the state transitions 
```
$ grep "^==== " wnrun.1.slipstream.log | sort | uniq -c | awk 'BEGIN {c=0} {c+=$1; print $0} END {print "total:", c}'
 239 ==== Executing ====
 240 ==== Provisioning ====
 239 ==== Ready ====
 239 ==== Sending report ====
total: 957
$ 
```

Excerpt from the log with the stacktrace

```
: 2015-03-03T11:19:06Z :
===============
==== Ready ====
===============

: 2015-03-03T14:21:25Z :
======================
==== Provisioning ====
======================
...

: 2015-03-10T15:10:01Z : 
ERROR: Error executing node, with detail: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/opt/slipstream/client/lib/slipstream/executors/MachineExecutor.py", line 58, in _execute
    getattr(self, 'on' + state)()
  File "/opt/slipstream/client/lib/slipstream/util.py", line 653, in overrided_func
    return func(self, *args, **kwargs)
  File "/opt/slipstream/client/lib/slipstream/executors/node/NodeDeploymentExecutor.py", line 62, in onProvisioning
    if self.wrapper.is_scale_state_creating():
  File "/opt/slipstream/client/lib/slipstream/wrappers/BaseWrapper.py", line 204, in is_scale_state_creating
    return self.SCALE_STATE_CREATING == self.get_scale_state()
  File "/opt/slipstream/client/lib/slipstream/wrappers/BaseWrapper.py", line 225, in get_scale_state
    return self._get_runtime_parameter(key)
  File "/opt/slipstream/client/lib/slipstream/wrappers/BaseWrapper.py", line 185, in _get_runtime_parameter
    return self._ss_client.getRuntimeParameter(key, ignoreAbort=ignore_abort)
  File "/opt/slipstream/client/lib/slipstream/SlipStreamHttpClient.py", line 219, in getRuntimeParameter
    _, content = self._httpGet(url, accept='text/plain')
  File "/opt/slipstream/client/lib/slipstream/SlipStreamHttpClient.py", line 244, in _httpGet
    return self.httpClient.get(url, accept, retry_number=self.http_max_retries)
  File "/opt/slipstream/client/lib/slipstream/HttpClient.py", line 55, in get
    return self._call(url, 'GET', accept=accept, retry_number=retry_number)
  File "/opt/slipstream/client/lib/slipstream/HttpClient.py", line 199, in _call
    resp, content = _request(_buildHeaders())
  File "/opt/slipstream/client/lib/slipstream/HttpClient.py", line 160, in _request
    resp, content = h.request(url, method, body, headers=headers)
  File "/opt/slipstream/client/lib/httplib2/__init__.py", line 1557, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/opt/slipstream/client/lib/httplib2/__init__.py", line 1363, in _request
    _updateCache(headers, response, content, self.cache, cachekey)
  File "/opt/slipstream/client/lib/httplib2/__init__.py", line 444, in _updateCache
    header_str = info.as_string()
  File "/usr/lib64/python2.6/email/message.py", line 135, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib64/python2.6/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib64/python2.6/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib64/python2.6/email/generator.py", line 161, in _write_headers
    header_name=h, continuation_ws='\t').encode()
  File "/usr/lib64/python2.6/email/header.py", line 176, in __init__
    self.append(s, charset, errors)
  File "/usr/lib64/python2.6/email/header.py", line 252, in append
    if charset != '8bit':
  File "/usr/lib64/python2.6/email/charset.py", line 241, in __ne__
    return not self.__eq__(other)
  File "/usr/lib64/python2.6/email/charset.py", line 238, in __eq__
    return str(self) == str(other).lower()
RuntimeError: maximum recursion depth exceeded
```

**Comment by schaubl** [comment]
We should transform the recursive method to a not recursive one.

**Comment by konstan** [comment]
Indeed.
